#!/bin/bash

url=https://roms.apon77.workers.dev/ccache/ppui/ccache.tar.gz # Where cccahe is located, use your ones, from where you want to download ccache!

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tmp/ccache.tar.gz since my file name is ccache.tar.gz
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process

# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
