#!/bin/bash
cd /dev/shm
git clone --filter=tree:0 https://github.com/AospExtended/platform_frameworks_base -b 11.x base
cd base
git remote add B1 https://github.com/ChintuOs/platform_frameworks_base
git fetch B1
git cherry-pick 9b7127a4bab70ddacba183d32e805b2ed3695e5b
git cherry-pick 52300592119f597ea11da92bb23d4413194aa1e5
git checkout -b auto
git push aponlab -f
