#!/bin/bash
cd /dev/shm
git clone --filter=tree:0 https://github.com/AospExtended/platform_frameworks_opt_telephony -b 11.x OPT
cd OPT
git remote add B2 https://github.com/ChintuOs/platform_frameworks_opt_telephony
git fetch B2
git cherry-pick f4cdb112493cb491727d8326d1dfc7422aedaa87^..913046a11e3a4099b0a5454cf759f8200de1b27a
git checkout -b auto
git push B2 -f
