name: aex fwb & telephony
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  job1:
    name: auto fwb & telephony
    runs-on: ubuntu-20.04
    env:
      GIT_PASS: ${{ secrets.GIT_PASS }}
    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
       ./config
    - name: framework base
      run: |
       ./fwb
    - name: framework opt telephony
      run: |
       ./opt_telephony
